language: ruby
rvm:
- 2.4.0
dist: trusty
sudo: false
addons:
  apt:
    packages:
    - python3
    - python3-yaml
    - python3-setuptools
    - python3-pandas
    - python3-pandas-lib
before_script:
- chmod +x ./scripts/build/*.py
- chmod +x ./scripts/build/*.sh
- chmod +x ./scripts/deploy/*.sh
script:
- python3 ./scripts/build/csvcheck.py
- python3 ./scripts/build/metadatacheck.py
- python3 ./scripts/build/configcheck.py
- scripts/build/cibuild.sh
deploy:
- provider: script
  script: scripts/deploy/deploy_staging.sh
  on:
    branch: develop
  skip_cleanup: true
- provider: script
  script: scripts/deploy/deploy.sh
  on:
    branch: master
  skip_cleanup: true
branches:
  only:
  - master
  - develop
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
